In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

In [3]:
data=pd.read_csv("inventory_dataset.csv")

In [4]:
data

,Product_ID,Product_Name,Category,Supplier,Purchase_Price,Sale_Price,Quantity_In_Stock,Reorder_Level,Units_On_Order,Discontinued
0,P0001,Doodad,Clothing,Supplier D,339.75,NaN,588.0,292.0,161.0,1
1,P0002,Doohickey,Clothing,Supplier C,NaN,470.14,348.0,114.0,70.0,1
2,P0003,Thingamajig,Clothing,Supplier B,NaN,460.10,146.0,199.0,163.0,1
3,P0004,Doohickey,Clothing,Supplier A,NaN,NaN,66.0,13.0,145.0,0
4,P0005,Doohickey,Toys,Supplier E,228.75,66.71,903.0,271.0,37.0,1
...,...,...,...,...,...,...,...,...,...,...
995,P0996,Gadget,Electronics,Supplier D,350.37,122.91,186.0,82.0,14.0,0
996,P0997,Widget,Toys,Supplier E,117.17,133.34,497.0,428.0,35.0,0
997,P0998,Widget,Electronics,Supplier C,301.70,241.22,441.0,72.0,62.0,0
998,P0999,Doodad,Toys,Supplier B,139.67,44.92,129.0,310.0,68.0,0
999,P1000,Thingamajig,Office Supplies,Supplier D,NaN,247.71,638.0,NaN,168.0,1

In [5]:
data.isnull().sum()

Product_ID             0
Product_Name           0
Category               0
Supplier               0
Purchase_Price       269
Sale_Price           259
Quantity_In_Stock     82
Reorder_Level         86
Units_On_Order       102
Discontinued           0
dtype: int64

In [6]:
data['Purchase_Price'].fillna(data['Purchase_Price'].median())

0      339.75
1      253.17
2      253.17
3      253.17
4      228.75
        ...
995    350.37
996    117.17
997    301.70
998    139.67
999    253.17
Name: Purchase_Price, Length: 1000, dtype: float64

In [7]:
data['Purchase_Price'].median()

253.17

In [8]:
data['Sale_Price'].fillna(data['Sale_Price'].mean())

0      351.926883
1      470.140000
2      460.100000
3      351.926883
4       66.710000
          ...
995    122.910000
996    133.340000
997    241.220000
998     44.920000
999    247.710000
Name: Sale_Price, Length: 1000, dtype: float64

In [9]:
data['Sale_Price'].mean()

351.92688259109315

In [10]:
data.dropna()

,Product_ID,Product_Name,Category,Supplier,Purchase_Price,Sale_Price,Quantity_In_Stock,Reorder_Level,Units_On_Order,Discontinued
4,P0005,Doohickey,Toys,Supplier E,228.75,66.71,903.0,271.0,37.0,1
6,P0007,Thingamajig,Furniture,Supplier A,412.99,230.48,121.0,215.0,136.0,1
7,P0008,Thingamajig,Electronics,Supplier A,430.21,267.92,339.0,444.0,199.0,1
9,P0010,Doohickey,Furniture,Supplier C,221.18,166.85,899.0,447.0,34.0,1
10,P0011,Doodad,Electronics,Supplier E,166.24,34.70,690.0,474.0,81.0,0
...,...,...,...,...,...,...,...,...,...,...
992,P0993,Doodad,Office Supplies,Supplier A,169.01,61.86,720.0,167.0,177.0,1
995,P0996,Gadget,Electronics,Supplier D,350.37,122.91,186.0,82.0,14.0,0
996,P0997,Widget,Toys,Supplier E,117.17,133.34,497.0,428.0,35.0,0
997,P0998,Widget,Electronics,Supplier C,301.70,241.22,441.0,72.0,62.0,0
998,P0999,Doodad,Toys,Supplier B,139.67,44.92,129.0,310.0,68.0,0

In [11]:
data

,Product_ID,Product_Name,Category,Supplier,Purchase_Price,Sale_Price,Quantity_In_Stock,Reorder_Level,Units_On_Order,Discontinued
0,P0001,Doodad,Clothing,Supplier D,339.75,NaN,588.0,292.0,161.0,1
1,P0002,Doohickey,Clothing,Supplier C,NaN,470.14,348.0,114.0,70.0,1
2,P0003,Thingamajig,Clothing,Supplier B,NaN,460.10,146.0,199.0,163.0,1
3,P0004,Doohickey,Clothing,Supplier A,NaN,NaN,66.0,13.0,145.0,0
4,P0005,Doohickey,Toys,Supplier E,228.75,66.71,903.0,271.0,37.0,1
...,...,...,...,...,...,...,...,...,...,...
995,P0996,Gadget,Electronics,Supplier D,350.37,122.91,186.0,82.0,14.0,0
996,P0997,Widget,Toys,Supplier E,117.17,133.34,497.0,428.0,35.0,0
997,P0998,Widget,Electronics,Supplier C,301.70,241.22,441.0,72.0,62.0,0
998,P0999,Doodad,Toys,Supplier B,139.67,44.92,129.0,310.0,68.0,0
999,P1000,Thingamajig,Office Supplies,Supplier D,NaN,247.71,638.0,NaN,168.0,1

In [12]:
Q1 = data['Sale_Price'].quantile(0.25)
Q2 = data['Sale_Price'].quantile(0.75)
IQR = Q2 - Q1

In [13]:
IQR

300.62

In [14]:
low = Q1 - 1.5 * IQR
up = Q2 + 1.5 * IQR

In [15]:
low

-293.54

In [16]:
up

908.94

In [17]:
data = data[(data['Sale_Price'] >= low) & (data['Sale_Price'] <= up)]

In [18]:
data

,Product_ID,Product_Name,Category,Supplier,Purchase_Price,Sale_Price,Quantity_In_Stock,Reorder_Level,Units_On_Order,Discontinued
1,P0002,Doohickey,Clothing,Supplier C,NaN,470.14,348.0,114.0,70.0,1
2,P0003,Thingamajig,Clothing,Supplier B,NaN,460.10,146.0,199.0,163.0,1
4,P0005,Doohickey,Toys,Supplier E,228.75,66.71,903.0,271.0,37.0,1
6,P0007,Thingamajig,Furniture,Supplier A,412.99,230.48,121.0,215.0,136.0,1
7,P0008,Thingamajig,Electronics,Supplier A,430.21,267.92,339.0,444.0,199.0,1
...,...,...,...,...,...,...,...,...,...,...
995,P0996,Gadget,Electronics,Supplier D,350.37,122.91,186.0,82.0,14.0,0
996,P0997,Widget,Toys,Supplier E,117.17,133.34,497.0,428.0,35.0,0
997,P0998,Widget,Electronics,Supplier C,301.70,241.22,441.0,72.0,62.0,0
998,P0999,Doodad,Toys,Supplier B,139.67,44.92,129.0,310.0,68.0,0
999,P1000,Thingamajig,Office Supplies,Supplier D,NaN,247.71,638.0,NaN,168.0,1

In [19]:
scaler = MinMaxScaler()
data.loc[:, 'Quantity_In_Stock'] = scaler.fit_transform(data[['Quantity_In_Stock']])

In [20]:
data.loc[:, 'Quantity_In_Stock']

1      0.348697
2      0.146293
4      0.904810
6      0.121242
7      0.339679
         ...
995    0.186373
996    0.497996
997    0.441884
998    0.129259
999    0.639279
Name: Quantity_In_Stock, Length: 731, dtype: float64

In [23]:
data.loc[:, 'Quantity_In_Stock'] = (data['Quantity_In_Stock'] * 100).fillna(0).astype(int)

In [24]:
data.loc[:, 'Quantity_In_Stock']

1      34.0
2      14.0
4      90.0
6      12.0
7      33.0
       ...
995    18.0
996    49.0
997    44.0
998    12.0
999    63.0
Name: Quantity_In_Stock, Length: 731, dtype: float64

In [25]:
label_encoder = LabelEncoder()
data.loc[:, 'Discontinued'] = label_encoder.fit_transform(data['Discontinued'])